"""modify some user roles

Revision ID: a38da8258d10
Revises: ba7489b262d2
Create Date: 2024-09-28 01:20:15.948993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a38da8258d10'
down_revision = 'ba7489b262d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ahli', schema=None) as batch_op:
        batch_op.drop_index('unique_id')

    op.drop_table('ahli')
    with op.batch_alter_table('petani', schema=None) as batch_op:
        batch_op.drop_index('unique_id')

    op.drop_table('petani')
    with op.batch_alter_table('regular_users', schema=None) as batch_op:
        batch_op.drop_index('unique_id')

    op.drop_table('regular_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regular_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('unique_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('nama_lengkap', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pekerjaan', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('kelamin', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('kota', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('kec', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('kelurahan', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bio', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profile_pic', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='regular_users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('regular_users', schema=None) as batch_op:
        batch_op.create_index('unique_id', ['unique_id'], unique=True)

    op.create_table('petani',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('unique_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('kebun', mysql.FLOAT(), nullable=True),
    sa.Column('luas_lahan', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='petani_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('petani', schema=None) as batch_op:
        batch_op.create_index('unique_id', ['unique_id'], unique=True)

    op.create_table('ahli',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('unique_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('institusi', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bidang_keahlian', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('gelar', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='ahli_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ahli', schema=None) as batch_op:
        batch_op.create_index('unique_id', ['unique_id'], unique=True)

    # ### end Alembic commands ###
