"""adding phone number column for personal user

Revision ID: df089da02e89
Revises: a38da8258d10
Create Date: 2024-10-29 21:32:07.386174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df089da02e89'
down_revision = 'a38da8258d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personals', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
